on: [push]

jobs:
  build:
    if: false
    runs-on: ubuntu-latest
    name: Build LSOracle
    container: ghcr.io/lnis-uofu/lsoracle-build:latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Build
        run: |
          cmake -DCMAKE_BUILD_TYPE=RELEASE -B build .
          cmake --build build -j$(nproc)
      - name: Run tests
        run: |
          python3 basic_tests.py --cicd
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: lsoracle-binary
          path: build/core/lsoracle
  benchmark:
    runs-on: ubuntu-latest
    name: Benchmarks
    container: ghcr.io/lnsi-uofu/lsoracle-benchmark:latest
    needs: build
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      # - name: Get binaries
      #   uses: actions/download-artifact@v2
      #   with:
      #     name: lsoracle-binary
      # - name: Get previous results
      #   uses: pozetroninc/github-action-get-latest-release@v0.5.5
      #   with:
      #     owner: lnis-uofu
      #     repo: LSOracle
      - name: Run synthesis
        run: |
          make LSORACLE=lsoracle everything.png -j$(nproc)
      - name: Archive results
        uses: actions/upload-artifact@v2
        with:
          name: benchmark-results
          path: |
            benchmarks/everything.tsv
            benchmarks/*/*.log
            benchmarks/*/*.rtl
            benchmarks/*/*.mapped.v
            benchmarks/*/*.synth_report
            benchmarks/*/*.timing
            benchmarks/*/*.report
            benchmarks/*/*.everything
      - name: Publish results
        uses: softprops/action-gh-release@v1
        #if: github.ref == 'refs/heads/master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            benchmarks/everything.tsv
            benchmarks/*/*.log
            benchmarks/*/*.rtl
            benchmarks/*/*.mapped.v
            benchmarks/*/*.synth_report
            benchmarks/*/*.timing
            benchmarks/*/*.report
            benchmarks/*/*.everything
          prerelease: true
