name: Local Runner Test

on:
  - push

jobs:
  benchmark:
    runs-on: self-hosted
    name: verification
    container: ghcr.io/lnis-uofu/lsoracle-benchmarks:groovy
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Get binaries
        uses: actions/download-artifact@v2
        with:
          name: lsoracle-binary
      - name: Prep previous
        run: |
          mkdir -p benchmarks/previous
      - name: Run synthesis
        run: |
          cp lsoracle /usr/local/bin
          chmod +x /usr/local/bin/lsoracle
          mkdir -p /usr/local/share/lsoracle
          cd benchmarks
          make everything.tsv -j $(nproc)
      - name: Get previous results
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          version: tags/cicd_test
          file: "everything.tsv"
          target: "benchmarks/previous/everything.tsv"
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Render results
        continue-on-error: true
        run: |
          cd benchmarks
          make everything.pdf
